fix(workspace): change root paths for projects in workspace.json
In the workspace.json the root properties have been changed to '.'
because there was a build error
on the library consumers
Error: "File is not under 'rootDir' .. 'rootDir' is expected to contain all
source files"